"""
File: word_guess.py
-------------------
Fill in this comment.
"""


import random


LEXICON_FILE = "Lexicon.txt"    # File to read word list from
INITIAL_GUESSES = 8             # Initial number of guesses player starts with


def play_game(secret_word):
    """
    This function will take the random word generated by the get_word function
    and allow the user to guess the word a set number of times. It will keep
    track of the players guesses and the number of guesses remaining.
    """

    num_guess = 0
    word_list = []
    guesses = ""
    word_list = secret_word
    word = ""
    # Convert secret_word to " - - - - - "
    guessed_word = []
    for i in range(len(secret_word)):
        guessed_word.append(" - ")


    # Allows the game to continue while user has guess left
    while num_guess < INITIAL_GUESSES:
        print("Your word now looks like this: " + word.join(guessed_word))
        print("You have " + str(INITIAL_GUESSES - num_guess) + " guesses left")
        guess = (input("Type a single letter here, then press enter: ")).upper()
        # Checks input for only a single alpha character
        if guess.isdigit():
            print("Only guess a letter: \n")
        elif len(guess) > 1:
            print("Only guess one letter: \n")
        elif guess in word_list:
            for i in range(len(secret_word)):
                if word_list[i] == guess:
                    guessed_word[i] = word_list[i]
                    print("That guess is correct!\n")
                    if word_list == word.join(guessed_word):
                        print("You Win!!\n")
                        exit()
        else:
            num_guess += 1
            print("There are no " + guess + "'s in the word \n")
    if num_guess >= INITIAL_GUESSES:
        print("You are out of turns!")
        print("The word was: " + str(word_list))

def get_word():
    """
    This function returns a secret word that the player is trying
    to guess in the game.  This function initially has a very small
    list of words that it can select from to make it easier for you
    to write and debug the main game playing program.  In Part II of
    writing this program, you will re-implement this function to
    select a word from a much larger list by reading a list of words
    from the file specified by the constant LEXICON_FILE.
    """
    """
    index = random.randrange(3)
    if index == 0:
        return 'HAPPY'
    elif index == 1:
        return 'PYTHON'
    else:
        return 'COMPUTER'
"""
    word_list = []
    file = open(LEXICON_FILE)
    for line in file:
        word = line.strip()
        word_list.append(word)
    return random.choice(word_list)

def main():
    """
    To play the game, we first select the secret word for the
    player to guess and then play the game using that secret word.
    """
    secret_word = get_word()
    play_game(secret_word)


# This provided line is required at the end of a Python file
# to call the main() function.
if __name__ == "__main__":
    main()